version: '3'

services:

  bots_redis:
    image: redis:latest
    container_name: bots_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}

  test_task_bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: test_task_bot
    restart: "no"
    depends_on:
      - "bots_redis"
    environment:
      - PYTHONUNBUFFERED=1
    command:
      - "python3"
      - "bot/main.py"